[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/immobilien/*"
  to = "https://master-uniquely--fantastic--toucan-pgsdemo-com.preview.pagescdn.com/:splat"
  status = 200
