[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/stores/*"
  to = "https://sharply-awful-fowl.pgsdemo.com/:splat"
  status = 200
