[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[headers]]
  for = "/*"
  [headers.values]
  x-yext-reverse-proxy = "true"

[[redirects]]
   from = "/*"
   to = "https://main-cleverly--dizzy--gamefowl-pgsdemo-com.preview.pagescdn.com/:splat"
   status = 200
