[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
   from = "/*"
   to = "https://urbanely-copper-mastiff.pgsdemo.com/:splat"
   status = 200
